name: 部署文档

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  deploy-gh-pages:
    runs-on: ubuntu-latest
    steps:
      # 在虚拟机（ubuntu）中，将GitHub仓库的文件克隆到虚拟机中
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          # 如果文档需要 Git 子模块，取消注释下一行
          # submodules: true

      # 在虚拟机（ubuntu）中，安装Node.js（搭建环境）
      - name: 设置 Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm

      # 在虚拟机（ubuntu）中，安装package.json中的依赖（因为.gitignore文件要求不上传依赖[node_modules]到GitHub远端仓库）
      - name: 安装依赖
        run: |
          corepack enable
          npm ci

      # 在虚拟机（ubuntu）中，使用docs:build命令构建/打包静态内容（HTML/CSS/JavaScript）到src/.vuepress/dist文件夹
      - name: 构建文档
        env:
          NODE_OPTIONS: --max_old_space_size=8192
        run: |-
          npm run docs:build
          > src/.vuepress/dist/.nojekyll

      # 在虚拟机（ubuntu）中，将src/.vuepress/dist文件夹中的内容部署到GitHub远端仓库的blog_pages分支
      - name: 部署文档
        uses: JamesIves/github-pages-deploy-action@v4
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        with:
          # 部署文档
          branch: blog_pages
          folder: src/.vuepress/dist
